POST http://localhost:8080/student/
Content-Type: application/json

{
    "name": "Bui Duc Thach",
    "gender": "Name",
    "dateOfBirth": "13/02/2021"
}

###################

POST http://localhost:8080/class/
Content-Type: application/json

{
    "name": "Tieng Viet"
}

###################

POST http://localhost:8080/parent/
Content-Type: application/json

{
    "name": "Bui A"
}

###################
PUT http://localhost:8080/student/1814062/
Content-Type: application/json

{
    "name": "Nguyen Van A"
}

###################
PUT http://localhost:8080/class/2002/
Content-Type: application/json

{
    "idClass":3000,
    "name": "Nguyen Van AA"
}

###################
PUT http://localhost:8080/parent/180000/
Content-Type: application/json

{
    "idParent":3000,
    "name": "Nguyen Van AA"
}

###################
DELETE http://localhost:8080/student/1814062/

###################
DELETE http://localhost:8080/class/2001/

##################
DELETE http://localhost:8080/parent/180005/

##################
GET  http://localhost:8080/student/1?idStudent=1814062&idClass=9999

##################
GET  http://localhost:8080/student/2?idStudent=1814062&idParent=180001

##################
GET  http://localhost:8080/student/filter

##################
GET  http://localhost:8080/student/user?search=Bui&limit=10&page=1&sort=dateOfBirth&filter=15/07/2021